name: MLflow Retraining CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  retrain-model:
    runs-on: ubuntu-latest
    permissions:
      contents: write # memberikan izin untuk push
    steps:
      # Langkah 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Langkah 2: Set up Conda
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.11"

      # Langkah 3: Install & Run dalam satu shell yang sama
      - name: Install MLflow and Run Project
        shell: bash -l {0}
        run: |
          pip install mlflow
          mlflow run MLProject/

      # Langkah 4: Commit dan Push Hasil Eksperimen 
      - name: Commit and Push MLflow Artifacts
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Pesan commit yang akan dibuat
          commit_message: "ci: [Automated] Add trained model artifacts [skip ci]"
          
          # Folder yang akan di-commit (folder output MLflow)
          file_pattern: mlruns/
          
          # Nama dan email untuk commit bot
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com